using AnimStudio.SharedKernel;

namespace AnimStudio.ContentModule.Domain.Events;

/// <summary>Raised when a script is first generated by the AI engine.</summary>
public sealed record ScriptGeneratedEvent(Guid ScriptId, Guid EpisodeId) : IDomainEvent;

/// <summary>Raised when the AI engine regenerates a script (overwriting the previous one).</summary>
public sealed record ScriptUpdatedEvent(Guid ScriptId, Guid EpisodeId) : IDomainEvent;

/// <summary>Raised when a user manually edits and saves the script.</summary>
public sealed record ScriptManuallyEditedEvent(Guid ScriptId, Guid EpisodeId) : IDomainEvent;
