using AnimStudio.ContentModule.Application.DTOs;
using AnimStudio.ContentModule.Application.Interfaces;
using AnimStudio.ContentModule.Domain.Enums;
using AnimStudio.SharedKernel;
using MediatR;

namespace AnimStudio.ContentModule.Application.Queries.GetAnimationClipSignedUrl;

/// <summary>
/// Returns a playback URL for a single rendered clip.
/// <para>
/// When <c>FileStorage:Provider = "Local"</c> the URL is a permanent
/// <c>/api/v1/files/…</c> path served by <c>FileStorageController</c>.
/// When <c>Provider = "AzureBlob"</c> the URL is a 60-second SAS URL
/// generated by <see cref="IFileStorageService"/> (via the Blob implementation).
/// Both cases use the same <see cref="IFileStorageService"/> abstraction so
/// the query handler is provider-agnostic.
/// </para>
/// </summary>
public sealed record GetAnimationClipSignedUrlQuery(Guid EpisodeId, Guid ClipId)
    : IRequest<Result<SignedClipUrlDto>>;

public sealed class GetAnimationClipSignedUrlHandler(
    IAnimationClipRepository clips,
    IFileStorageService fileStorage)
    : IRequestHandler<GetAnimationClipSignedUrlQuery, Result<SignedClipUrlDto>>
{
    public async Task<Result<SignedClipUrlDto>> Handle(
        GetAnimationClipSignedUrlQuery query, CancellationToken ct)
    {
        var clip = await clips.GetByIdAsync(query.ClipId, ct);
        if (clip is null || clip.EpisodeId != query.EpisodeId)
            return Result<SignedClipUrlDto>.Failure("Clip not found.", "NOT_FOUND");

        if (clip.Status != ClipStatus.Ready || string.IsNullOrWhiteSpace(clip.ClipUrl))
            return Result<SignedClipUrlDto>.Failure(
                "Clip is not yet ready for playback.", "CLIP_NOT_READY");

        var url = fileStorage.GetFileUrl(clip.ClipUrl);

        // Local provider: URL never expires — use a far-future sentinel.
        // Blob provider: GetFileUrl() embeds a SAS token; we report 1-hour TTL.
        var expiresAt = DateTimeOffset.UtcNow.AddHours(1);

        return Result<SignedClipUrlDto>.Success(new SignedClipUrlDto(clip.Id, url, expiresAt));
    }
}
